### ISSUE TITLE
Test succession incohérent avec date de validité de paramètre

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france-inheritance#7]
Dans le fichier `tests/succession/homme_marie_3_enf.yaml`, le test suivant échoue :

```yaml
- name: Succession homme marié sans enfants
  description: test
  period: 2022
  input:
    individus:
      papa:
        date_deces: 2022-01-01
      maman:
        date_deces: 9999-01-01
    successions:
      succession_0:
        decede: papa
        epoux_survivant: maman
        actif_propre: 1_000_000

  output:
    epoux_survivant: 1
    actif_imposable: 1_000_000
    part_taxable: 924_000
```

Lorsqu'on exécute la commande suivante : `poetry run openfisca test -c openfisca_france_inheritance tests/`
Le message obtenu est alors :

```sh
$ poetry run openfisca test -c openfisca_france_inheritance tests/
============================== test session starts ==============================
platform darwin -- Python 3.11.11, pytest-8.3.5, pluggy-1.5.0
rootdir: /.../openfisca-france-inheritance
configfile: pyproject.toml
plugins: time-machine-2.16.0
collected 9 items                                                               

tests/donation/celib_frere_don.yaml .                                     [ 11%]
tests/donation/homme_marie_3_enf_don.yaml ..                              [ 22%]
tests/donation/veuf_2_enfants_don.yaml .                                  [ 33%]
tests/succession/celib_frere.yaml .                                       [ 44%]
tests/succession/homme_marie_3_enf.yaml F

=================================== FAILURES ====================================
_________________________________ test session __________________________________
/.../openfisca-france-inheritance/tests/succession/homme_marie_3_enf.yaml:
  Test 'Succession homme marié sans enfants':
    part_taxable@2022: [0.] differs from 924000.0 with an absolute margin [924000.] > 0
``` 

La valeur `924000` attendue par le test semble incohérente avec ce que l'on observe la `formula_2008` de `part_taxable` pour 1 conjoint (`epoux_survivant: 1` dans le test) ; en effet, `part_taxable_epoux_survivant` y est fixée à zéro.

D'où les questions suivantes : 
* le test doit-il être corrigé ? C'est ce que l'on fait temporairement dans #5. 
* ou la formule doit-elle être corrigée ? Ceci sachant qu'en lecture très rapide, la [référence législative du paramètre de la formule précédente pour la même situation d'époux survivant `openfisca_france_inheritance/parameters/droits_mutation_titre_gratuit/abattement/conjoint/succession.yaml`](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000001502171) ne semble pas abroger l'abattement (et donc pas l'existence d'une part taxable).
